; ============================================================
;  platformio.ini — Configuración del proyecto PlatformIO
;  Placa  : DOIT ESP32 DEVKIT V1
;  Materia: Programación Orientada a Objetos
; ============================================================

[env:esp32doit-devkit-v1]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino

upload_port   = COM4
; Velocidad de subida (opcional, aumentar si es lenta)
upload_speed = 115200


; Monitor Serial a 115200 (igual que Serial.begin en main.cpp)
monitor_speed = 115200

; Librerías — PlatformIO las descarga automáticamente
lib_deps =
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    fmalpartida/LiquidCrystal @ ^1.5.0
